# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_writing'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lang',
            field=models.CharField(choices=[('en', 'english'), ('es', 'spanish')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='moto',
            name='lang',
            field=models.CharField(choices=[('en', 'english'), ('es', 'spanish')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='lang',
            field=models.CharField(choices=[('en', 'english'), ('es', 'spanish')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='writing',
            name='lang',
            field=models.CharField(choices=[('en', 'english'), ('es', 'spanish')], default='en', max_length=2),
        ),
    ]
