# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170831_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortinfo',
            name='lang',
            field=models.CharField(choices=[(b'en', b'english'), (b'es', b'spanish')], default=b'en', max_length=2),
        ),
    ]
