# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170908_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
